steps:
  - id: 'terraform init'
    name: 'hashicorp/terraform:light'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "********************"
        echo "OK"
        terraform init -backend-config="prefix=env/OK"
    
  - id: 'terraform plan'
    name: 'hashicorp/terraform:light'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform plan -var="branch_name=OK" -var-file="terraform.tfvars"
    
  - id: 'terraform apply'
    name: 'hashicorp/terraform:light'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform apply -var="branch_name=OK" -var-file="terraform.tfvars" --auto-approve

options:
  logging: CLOUD_LOGGING_ONLY
