steps:
  - id: 'terraform init'
    name: 'hashicorp/terraform:light'
    entrypoint: '/bin/sh'
    args:
      - 'c'
      - |
        export TF_VAR_backend_prefix=$BRANCH_NAME
        terraform init
    
  - id: 'terraform plan'
    name: 'hashicorp/terraform:light'
    script: terraform plan -var-file="terraform.tfvars"
    
  - id: 'terraform apply'
    name: 'hashicorp/terraform:light'
    script: terraform apply -var-file="terraform.tfvars" --auto-approve

options:
  logging: CLOUD_LOGGING_ONLY
