steps:
  - id: 'terraform init'
    name: 'hashicorp/terraform:light'
    script: terraform init -backend-config="prefix=env/adding_terraform_variables"
    env:
      - TF_LOG=DEBUG
    
  - id: 'terraform plan'
    name: 'hashicorp/terraform:light'
    script: terraform plan -var="branch_name=adding_terraform_variables" -var-file="terraform.tfvars"
    env:
      - TF_LOG=DEBUG
    
  - id: 'terraform apply'
    name: 'hashicorp/terraform:light'
    script: terraform apply -var="branch_name=adding_terraform_variables" -var-file="terraform.tfvars" --auto-approve
    env:
      - TF_LOG=DEBUG
    
options:
  logging: CLOUD_LOGGING_ONLY
